"""expand trace_id length

Revision ID: 0da14c04b8a5
Revises: d1f2e3a4b5c6
Create Date: 2026-03-28 08:09:54.588549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0da14c04b8a5'
down_revision: Union[str, Sequence[str], None] = 'd1f2e3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversation_states_intent'), table_name='conversation_states')
    op.drop_index(op.f('idx_conversation_states_user'), table_name='conversation_states')
    op.create_index(op.f('ix_conversation_states_active_intent'), 'conversation_states', ['active_intent'], unique=False)
    op.create_index(op.f('ix_conversation_states_user_id'), 'conversation_states', ['user_id'], unique=False)
    op.alter_column('processed_messages', 'trace_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.drop_index(op.f('idx_execution_reclaim'), table_name='processed_messages', postgresql_where="(status = 'EXECUTING'::execution_status_enum)")
    op.create_index(op.f('ix_processed_messages_user_id'), 'processed_messages', ['user_id'], unique=False)
    op.drop_column('processed_messages', 'execution_started_at')
    op.alter_column('workflow_events', 'trace_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_events', 'trace_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('processed_messages', sa.Column('execution_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_processed_messages_user_id'), table_name='processed_messages')
    op.create_index(op.f('idx_execution_reclaim'), 'processed_messages', ['status', 'dispatch_started_at'], unique=False, postgresql_where="(status = 'EXECUTING'::execution_status_enum)")
    op.alter_column('processed_messages', 'trace_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_conversation_states_user_id'), table_name='conversation_states')
    op.drop_index(op.f('ix_conversation_states_active_intent'), table_name='conversation_states')
    op.create_index(op.f('idx_conversation_states_user'), 'conversation_states', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversation_states_intent'), 'conversation_states', ['active_intent'], unique=False)
    # ### end Alembic commands ###
