"""initial_full_schema

Revision ID: 3d60ce943cab
Revises: 
Create Date: 2026-02-25 15:40:33.926044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d60ce943cab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_store',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_store_phone'), 'otp_store', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('shipper', 'transporter', 'both', name='userrole'), nullable=True),
    sa.Column('kyc_status', sa.Enum('pending', 'under_review', 'verified', 'rejected', name='kycstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('wa_onboarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('aadhaar', 'pan', 'rc_book', 'driving_license', 'gst', name='doctype'), nullable=False),
    sa.Column('doc_number', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipper_id', sa.UUID(), nullable=False),
    sa.Column('from_city', sa.String(length=100), nullable=False),
    sa.Column('to_city', sa.String(length=100), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('goods_type', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=False),
    sa.Column('budget_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'matched', 'confirmed', 'completed', 'cancelled', name='loadrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shipper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trucks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('truck_type', sa.Enum('mini', 'medium', 'large', 'trailer', name='trucktype'), nullable=False),
    sa.Column('total_capacity_kg', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('truck_space_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('from_city', sa.String(length=100), nullable=False),
    sa.Column('to_city', sa.String(length=100), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('total_capacity_kg', sa.Integer(), nullable=False),
    sa.Column('available_capacity_kg', sa.Integer(), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'partial', 'full', 'completed', 'cancelled', name='listingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('load_request_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('agreed_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipper_confirmed', sa.Boolean(), nullable=False),
    sa.Column('transporter_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'accepted', 'rejected', 'completed', name='matchstatus'), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['truck_space_listings.id'], ),
    sa.ForeignKeyConstraint(['load_request_id'], ['load_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('truck_space_listings')
    op.drop_table('trucks')
    op.drop_table('load_requests')
    op.drop_table('kyc_documents')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_store_phone'), table_name='otp_store')
    op.drop_table('otp_store')
    # ### end Alembic commands ###
