"""Unbreakable v2 upgrades

Revision ID: 42095dfa6eba
Revises: b3cc604670ef
Create Date: 2026-03-20 15:33:34.896054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42095dfa6eba'
down_revision: Union[str, Sequence[str], None] = 'b3cc604670ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🔥 DATA CLEANUP (Safe for dedupe table during infra shift)
    op.execute("DELETE FROM processed_messages")
    
    op.add_column('events', sa.Column('trace_id', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_events_trace_id'), 'events', ['trace_id'], unique=False)
    op.add_column('processed_messages', sa.Column('idempotency_key', sa.String(length=255), nullable=False))
    op.add_column('processed_messages', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('processed_messages', sa.Column('response_payload', sa.JSON(), nullable=True))
    op.add_column('processed_messages', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('processed_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_processed_messages_wa_message_id'), table_name='processed_messages')
    op.create_index(op.f('ix_processed_messages_idempotency_key'), 'processed_messages', ['idempotency_key'], unique=True)
    op.drop_column('processed_messages', 'wa_message_id')
    
    # 🔥 FIX: Add state as nullable first, then populate, then make NOT NULL
    op.add_column('users', sa.Column('state', sa.String(length=50), nullable=True))
    op.execute("UPDATE users SET state = 'IDLE'")
    op.alter_column('users', 'state', nullable=False)
    
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'state')
    op.add_column('processed_messages', sa.Column('wa_message_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_processed_messages_idempotency_key'), table_name='processed_messages')
    op.create_index(op.f('ix_processed_messages_wa_message_id'), 'processed_messages', ['wa_message_id'], unique=True)
    op.drop_column('processed_messages', 'updated_at')
    op.drop_column('processed_messages', 'expires_at')
    op.drop_column('processed_messages', 'response_payload')
    op.drop_column('processed_messages', 'status')
    op.drop_column('processed_messages', 'idempotency_key')
    op.drop_index(op.f('ix_events_trace_id'), table_name='events')
    op.drop_column('events', 'raw_data')
    op.drop_column('events', 'trace_id')
    # ### end Alembic commands ###
