"""Add stabilization columns

Revision ID: 76053ffd589b
Revises: 9a1b2c3d4e5f
Create Date: 2026-03-23 16:21:16.329808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76053ffd589b'
down_revision: Union[str, Sequence[str], None] = '9a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processed_messages', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processed_messages', sa.Column('execution_duration_ms', sa.Integer(), nullable=True))
    op.add_column('processed_messages', sa.Column('dispatch_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processed_messages', sa.Column('replay_execution_hash', sa.String(length=128), nullable=True))
    op.alter_column('processed_messages', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('processed_messages', 'recovery_attempted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('processed_messages', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('processed_messages', 'execution_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_execution_reclaim'), table_name='processed_messages', postgresql_where="((status)::text = 'EXECUTING'::text)")
    op.drop_constraint(op.f('idx_idempotency_key'), 'processed_messages', type_='unique')
    op.create_index('idx_delivered_at', 'processed_messages', ['delivered_at'], unique=False)
    op.create_index('idx_failed_at', 'processed_messages', ['failed_at'], unique=False)
    op.create_index('idx_read_at', 'processed_messages', ['read_at'], unique=False)
    op.drop_index(op.f('idx_user_id'), table_name='users')
    op.drop_index(op.f('idx_user_phone'), table_name='users')
    op.drop_index(op.f('idx_user_updated_at'), table_name='users')
    op.add_column('workflow_events', sa.Column('state_snapshot_hash', sa.String(length=128), nullable=True))
    op.alter_column('workflow_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_workflow_events_processed_message_id'), 'workflow_events', ['processed_message_id'], unique=False)
    op.drop_constraint(op.f('workflow_events_processed_message_id_fkey'), 'workflow_events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('workflow_events_processed_message_id_fkey'), 'workflow_events', 'processed_messages', ['processed_message_id'], ['id'])
    op.drop_index(op.f('ix_workflow_events_processed_message_id'), table_name='workflow_events')
    op.alter_column('workflow_events', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('workflow_events', 'state_snapshot_hash')
    op.create_index(op.f('idx_user_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('idx_user_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('idx_user_id'), 'users', ['id'], unique=False)
    op.drop_index('idx_read_at', table_name='processed_messages')
    op.drop_index('idx_failed_at', table_name='processed_messages')
    op.drop_index('idx_delivered_at', table_name='processed_messages')
    op.create_unique_constraint(op.f('idx_idempotency_key'), 'processed_messages', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_execution_reclaim'), 'processed_messages', ['status', 'execution_started_at'], unique=False, postgresql_where="((status)::text = 'EXECUTING'::text)")
    op.alter_column('processed_messages', 'execution_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('processed_messages', 'delivered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('processed_messages', 'recovery_attempted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('processed_messages', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('processed_messages', 'replay_execution_hash')
    op.drop_column('processed_messages', 'dispatch_started_at')
    op.drop_column('processed_messages', 'execution_duration_ms')
    op.drop_column('processed_messages', 'failed_at')
    op.drop_column('processed_messages', 'read_at')
    # ### end Alembic commands ###
