"""Add index to route_subscriptions for user and lane

Revision ID: b33e2a1be34d
Revises: de332aed62b2
Create Date: 2026-04-13 14:35:05.444155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33e2a1be34d'
down_revision: Union[str, Sequence[str], None] = 'de332aed62b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_route_sub_user_lane', 'route_subscriptions', ['user_id', 'lane_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_route_sub_user_lane', table_name='route_subscriptions')
    # ### end Alembic commands ###
