"""Add intelligence layer fields

Revision ID: b3cc604670ef
Revises: b2c3d4e5f6a7
Create Date: 2026-03-17 13:07:01.383214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cc604670ef'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_load_requests_expires_at'), table_name='load_requests')
    op.drop_index(op.f('idx_wa_message_id'), table_name='processed_messages')
    op.drop_constraint(op.f('uq_processed_messages_wa_message_id'), 'processed_messages', type_='unique')
    op.create_index(op.f('ix_processed_messages_wa_message_id'), 'processed_messages', ['wa_message_id'], unique=True)
    op.drop_index(op.f('idx_route_sub_user'), table_name='route_subscriptions')
    op.drop_constraint(op.f('route_subscriptions_user_id_fkey'), 'route_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'route_subscriptions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_truck_listings_expires_at'), table_name='truck_space_listings')
    op.create_index(op.f('ix_truck_space_listings_expires_at'), 'truck_space_listings', ['expires_at'], unique=False)
    op.drop_index(op.f('idx_user_activity_user_id'), table_name='user_activity')
    op.add_column('users', sa.Column('memory_data', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('users', sa.Column('completion_rate', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('users', sa.Column('cancellation_rate', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('users', sa.Column('rating', sa.Float(), server_default='5.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    op.drop_column('users', 'cancellation_rate')
    op.drop_column('users', 'completion_rate')
    op.drop_column('users', 'memory_data')
    op.create_index(op.f('idx_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.drop_index(op.f('ix_truck_space_listings_expires_at'), table_name='truck_space_listings')
    op.create_index(op.f('idx_truck_listings_expires_at'), 'truck_space_listings', ['expires_at'], unique=False)
    op.drop_constraint(None, 'route_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('route_subscriptions_user_id_fkey'), 'route_subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_route_sub_user'), 'route_subscriptions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_processed_messages_wa_message_id'), table_name='processed_messages')
    op.create_unique_constraint(op.f('uq_processed_messages_wa_message_id'), 'processed_messages', ['wa_message_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_wa_message_id'), 'processed_messages', ['wa_message_id'], unique=True)
    op.create_index(op.f('idx_load_requests_expires_at'), 'load_requests', ['expires_at'], unique=False)
    # ### end Alembic commands ###
