"""Phase 5 upgrades

Revision ID: bea3a2fdc311
Revises: e4beca38def9
Create Date: 2026-03-15 12:11:38.789998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bea3a2fdc311'
down_revision: Union[str, Sequence[str], None] = 'e4beca38def9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('rated_user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['rated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_match_id'), 'ratings', ['match_id'], unique=False)
    op.create_index(op.f('ix_ratings_rated_user_id'), 'ratings', ['rated_user_id'], unique=False)
    op.add_column('user_sessions', sa.Column('session_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('shipper_rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('transporter_rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('completed_trips', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating_count')
    op.drop_column('users', 'completed_trips')
    op.drop_column('users', 'transporter_rating')
    op.drop_column('users', 'shipper_rating')
    op.drop_column('user_sessions', 'session_data')
    op.drop_index(op.f('ix_ratings_rated_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_match_id'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
