"""Add lane_key and last_notified_at to RouteSubscription

Revision ID: de332aed62b2
Revises: 69bb0af21ebf
Create Date: 2026-04-13 14:27:28.296966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de332aed62b2'
down_revision: Union[str, Sequence[str], None] = '69bb0af21ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_subscriptions', sa.Column('lane_key', sa.String(length=200), nullable=True))
    op.add_column('route_subscriptions', sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_route_sub_lane_key', 'route_subscriptions', ['lane_key'], unique=False)
    op.drop_index(op.f('idx_owner_lane_vehicle_open_partial'), table_name='truck_space_listings', postgresql_where="(status = ANY (ARRAY['open'::listingstatus, 'partial'::listingstatus]))")
    op.create_index(op.f('ix_truck_space_listings_vehicle_type'), 'truck_space_listings', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_space_listings_vehicle_type'), table_name='truck_space_listings')
    op.create_index(op.f('idx_owner_lane_vehicle_open_partial'), 'truck_space_listings', ['owner_id', 'canonical_lane_key', 'vehicle_type'], unique=False, postgresql_where="(status = ANY (ARRAY['open'::listingstatus, 'partial'::listingstatus]))")
    op.drop_index('idx_route_sub_lane_key', table_name='route_subscriptions')
    op.drop_column('route_subscriptions', 'last_notified_at')
    op.drop_column('route_subscriptions', 'lane_key')
    # ### end Alembic commands ###
