"""loadmatch_upgrades_schema

Revision ID: e4beca38def9
Revises: 3d60ce943cab
Create Date: 2026-03-14 14:08:13.078604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4beca38def9'
down_revision: Union[str, Sequence[str], None] = '3d60ce943cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cargocategory = postgresql.ENUM('agriculture', 'food', 'steel', 'cement', 'chemicals', 'machinery', 'textiles', 'electronics', 'consumer_goods', 'fragile', 'hazardous', name='cargocategory')
    cargocategory.create(op.get_bind(), checkfirst=True)
    
    kycflowstate = postgresql.ENUM('not_started', 'aadhaar_uploaded', 'pan_uploaded', 'rc_uploaded', 'license_uploaded', 'under_review', 'verified', 'rejected', name='kycflowstate')
    kycflowstate.create(op.get_bind(), checkfirst=True)
    
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'pending'")
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'confirmed'")
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'in_transit'")
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'delivered'")
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'cancelled'")
    op.execute("ALTER TYPE matchstatus ADD VALUE IF NOT EXISTS 'expired'")

    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('current_workflow', sa.String(length=100), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('expected_input', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=False)
    op.add_column('load_requests', sa.Column('category', sa.Enum('agriculture', 'food', 'steel', 'cement', 'chemicals', 'machinery', 'textiles', 'electronics', 'consumer_goods', 'fragile', 'hazardous', name='cargocategory'), nullable=True))
    op.add_column('matches', sa.Column('booking_code', sa.String(length=50), nullable=True))
    op.add_column('matches', sa.Column('driver_lat', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('driver_lng', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('eta', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_matches_booking_code'), 'matches', ['booking_code'], unique=True)
    op.add_column('truck_space_listings', sa.Column('allowed_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=10), server_default='en', nullable=False))
    op.add_column('users', sa.Column('kyc_flow_state', sa.Enum('not_started', 'aadhaar_uploaded', 'pan_uploaded', 'rc_uploaded', 'license_uploaded', 'under_review', 'verified', 'rejected', name='kycflowstate'), server_default='not_started', nullable=False))
    op.drop_column('users', 'kyc_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_status', postgresql.ENUM('pending', 'under_review', 'verified', 'rejected', name='kycstatus'), autoincrement=False, nullable=False))
    op.drop_column('users', 'kyc_flow_state')
    op.drop_column('users', 'language')
    op.drop_column('truck_space_listings', 'allowed_categories')
    op.drop_index(op.f('ix_matches_booking_code'), table_name='matches')
    op.drop_column('matches', 'eta')
    op.drop_column('matches', 'driver_lng')
    op.drop_column('matches', 'driver_lat')
    op.drop_column('matches', 'booking_code')
    op.drop_column('load_requests', 'category')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
