from enum import Enum

class Intent(str, Enum):
    CREATE_LOAD = "CREATE_LOAD"
    POST_TRUCK = "POST_TRUCK"
    VIEW_LOADS = "VIEW_LOADS"
    VIEW_TRUCKS = "VIEW_TRUCKS"
    UPLOAD_KYC = "UPLOAD_KYC"
    RATE_TRIP = "RATE_TRIP"
    TRACK_TRUCK = "TRACK_TRUCK"
    CONTACT_DRIVER = "CONTACT_DRIVER"
    CONFIRM_BOOKING = "CONFIRM_BOOKING"
    GREETING = "GREETING"
    MENU = "MENU"
    UNKNOWN = "UNKNOWN"
    CONFIRM = "CONFIRM"
    CANCEL = "CANCEL"
